version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
  post:
    # build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${COMM_VER}
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus:${PROMETHEUS_VER}
    networks:
      - back_net
      - front_net
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
