{
 "title": "Service Monitoring",
 "time": { "from": "2020-05-30T16:21:56.021Z", "to": "2020-05-30T16:22:18.599Z" },
 "panels": [
  {
   "title": "95 Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Bad requests",
   "type": "graph",
   "description": "Description",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "This is description",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count{}[1m])" }
   ]
  }
 ]
}